[[libraries]]
location = [0,0,0]
"qaq" = "True"

[[libraries]]
location = [0,1,0]
"qaq" = "True"
"ead" = "False"


[[libraries]]
location = [0,0,1]
"qaq" = "True"

[[entities]]
name = "bob"
type = "Player"
# holding.item = "focus"
# holding.value = "true"

